version = 1

test_patterns = ["test/**"]

exclude_patterns = ["dist/*min.js"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "mongo",
    "browser"
  ]